const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),Database=require('better-sqlite3');
const PORT=process.env.PORT||3000,HOST='0.0.0.0';
const DATA_DIR=path.join(__dirname,'data'); if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
const db=new Database(path.join(DATA_DIR,'quickdrop.db'));
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY, customer TEXT, pickup TEXT, dropoff TEXT, km REAL, type TEXT, weight_extra INTEGER, price INTEGER, status TEXT, assigned_to TEXT, route TEXT, created_at TEXT);`);
const SECRET=process.env.QD_SECRET||'CHANGE_THIS_SECRET_IN_PRODUCTION';
const OTP_TTL=5*60*1000; const otpStore=new Map(); const rate=new Map();
const users={admin:{role:'admin',password:process.env.ADMIN_PASSWORD||'QDrop@2026'},partner:{role:'partner',password:process.env.PARTNER_PASSWORD||'QDrop@2026'}};
function token(user){let p=Buffer.from(JSON.stringify({u:user,exp:Date.now()+86400000})).toString('base64url');let s=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');return p+'.'+s}
function auth(req){let m=(req.headers.cookie||'').match(/qd_session=([^;]+)/);if(!m)return null;let [p,s]=m[1].split('.');try{if(crypto.createHmac('sha256',SECRET).update(p).digest('base64url')!==s)return null;let x=JSON.parse(Buffer.from(p,'base64url'));if(x.exp<Date.now()||!users[x.u])return null;return {username:x.u,role:users[x.u].role}}catch{return null}}
function safeEq(a,b){const A=Buffer.from(String(a));const B=Buffer.from(String(b));return A.length===B.length&&crypto.timingSafeEqual(A,B)}
function allow(key,limit=10,window=60000){const now=Date.now(),x=rate.get(key)||[];const y=x.filter(t=>now-t<window);if(y.length>=limit)return false;y.push(now);rate.set(key,y);return true}
async function sendSms(phone,code){if(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_FROM_NUMBER){const auth=Buffer.from(process.env.TWILIO_ACCOUNT_SID+':'+process.env.TWILIO_AUTH_TOKEN).toString('base64');const form=new URLSearchParams({To:phone,From:process.env.TWILIO_FROM_NUMBER,Body:`Your Fatehpur QuickDrop OTP is ${code}. It expires in 5 minutes.`});const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body:form});if(!r.ok)throw new Error('SMS provider error');return true}return false}
function json(res,status,obj,extra={}){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store',...extra});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',x=>{d+=x;if(d.length>1e6)req.destroy()});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}})})}
function row(r){return r&&{id:r.id,customer:r.customer,p:r.pickup,d:r.dropoff,km:r.km,type:r.type,weightExtra:r.weight_extra,price:'₹'+r.price,status:r.status,assignedTo:r.assigned_to,route:r.route?JSON.parse(r.route):null,time:new Date(r.created_at).toLocaleString()}}
const server=http.createServer(async(req,res)=>{try{
 if(req.method==='GET'&&req.url==='/api/me'){let a=auth(req);return json(res,200,{authenticated:!!a,user:a})}
 if(req.method==='POST'&&req.url==='/api/staff/login'){let ip=req.socket.remoteAddress||'unknown';if(!allow('staff:'+ip,8))return json(res,429,{error:'Too many login attempts'});let b=await body(req),u=String(b.username||''),p=String(b.password||''),x=users[u];if(!x||!safeEq(p,x.password))return json(res,401,{error:'Invalid staff credentials'});return json(res,200,{ok:true,user:{username:u,role:x.role}},{'Set-Cookie':`qd_session=${token(u)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400`})}
 if(req.method==='POST'&&req.url==='/api/customer/send-otp'){let b=await body(req),phone=String(b.phone||'').replace(/\s+/g,'');if(!/^\+?[0-9]{10,15}$/.test(phone))return json(res,400,{error:'Enter a valid mobile number'});if(!allow('otp:'+phone,3,10*60*1000))return json(res,429,{error:'Please wait before requesting another OTP'});let code=String(crypto.randomInt(100000,1000000));otpStore.set(phone,{code,exp:Date.now()+OTP_TTL});let sent=false;try{sent=await sendSms(phone,code)}catch(e){console.error(e)}return json(res,200,{ok:true,sent,devOtp:sent?undefined:code,expiresIn:OTP_TTL/1000})}
if(req.method==='POST'&&req.url==='/api/customer/verify-otp'){let b=await body(req),phone=String(b.phone||'').replace(/\s+/g,''),code=String(b.code||''),x=otpStore.get(phone);if(!x||x.exp<Date.now()||!safeEq(code,x.code))return json(res,401,{error:'Invalid or expired OTP'});otpStore.delete(phone);let t=token('customer:'+phone);return json(res,200,{ok:true,customer:phone},{'Set-Cookie':`qd_customer=${t}; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400`})}
if(req.method==='POST'&&req.url==='/api/logout')return json(res,200,{ok:true},{'Set-Cookie':'qd_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0','Set-Cookie-2':'qd_customer=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});
 if(req.method==='GET'&&req.url==='/api/orders'){let a=auth(req);if(a&&['admin','partner'].includes(a.role)){let q=a.role==='admin'?db.prepare('SELECT * FROM orders ORDER BY created_at DESC').all():db.prepare("SELECT * FROM orders WHERE assigned_to=? OR assigned_to IS NULL ORDER BY created_at DESC").all(a.username);return json(res,200,q.map(row))}let c=(req.headers.cookie||'').match(/qd_customer=([^;]+)/);if(c){try{let [pp,ss]=c[1].split('.');if(safeEq(crypto.createHmac('sha256',SECRET).update(pp).digest('base64url'),ss)){let x=JSON.parse(Buffer.from(pp,'base64url'));if(x.exp>Date.now()&&String(x.u).startsWith('customer:')){let phone=String(x.u).slice(9);let q=db.prepare('SELECT * FROM orders WHERE customer=? ORDER BY created_at DESC').all(phone);return json(res,200,q.map(row))}}}catch{}}return json(res,403,{error:'Authentication required'})}
 if(req.method==='POST'&&req.url==='/api/orders'){let c=(req.headers.cookie||'').match(/qd_customer=([^;]+)/);if(!c)return json(res,403,{error:'Customer login required'});let b=await body(req);let id=b.id||'QD'+Date.now().toString().slice(-6),now=new Date().toISOString();let price=Math.round(Number(String(b.price||'0').replace('₹','')));db.prepare('INSERT INTO orders(id,customer,pickup,dropoff,km,type,weight_extra,price,status,assigned_to,route,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,String(b.customer||''),b.p,b.d,Number(b.km||0),b.type||'Parcel',Number(b.weightExtra||0),price,'Pending',null,b.route?JSON.stringify(b.route):null,now);return json(res,201,row(db.prepare('SELECT * FROM orders WHERE id=?').get(id)))}
 let m=req.url.match(/^\/api\/orders\/([^/]+)\/assign$/);if(m&&req.method==='POST'){let a=auth(req);if(!a||a.role!=='admin')return json(res,403,{error:'Admin only'});let b=await body(req),name=b.username||null,o=db.prepare('SELECT * FROM orders WHERE id=?').get(m[1]);if(!o)return json(res,404,{error:'Order not found'});db.prepare('UPDATE orders SET assigned_to=? WHERE id=?').run(name,m[1]);return json(res,200,row(db.prepare('SELECT * FROM orders WHERE id=?').get(m[1])))}
 m=req.url.match(/^\/api\/orders\/([^/]+)\/status$/);if(m&&req.method==='POST'){let a=auth(req);if(!a||!['admin','partner'].includes(a.role))return json(res,403,{error:'Staff only'});let b=await body(req),o=db.prepare('SELECT * FROM orders WHERE id=?').get(m[1]);if(!o)return json(res,404,{error:'Order not found'});if(a.role==='partner'&&o.assigned_to!==a.username)return json(res,403,{error:'Order not assigned to this partner'});if(!['Pending','Accepted','Out for delivery','Delivered'].includes(b.status))return json(res,400,{error:'Invalid status'});db.prepare('UPDATE orders SET status=? WHERE id=?').run(b.status,m[1]);return json(res,200,row(db.prepare('SELECT * FROM orders WHERE id=?').get(m[1])))}
 if(req.method==='GET'){let f=req.url==='/'?'/index.html':req.url;if(f.includes('..'))return json(res,400,{error:'Bad path'});let fp=path.join(__dirname,'public',f);if(fs.existsSync(fp)){let ext=path.extname(fp),ct={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':ct});return res.end(fs.readFileSync(fp))}}
 json(res,404,{error:'Not found'});
}catch(e){console.error(e);json(res,500,{error:'Server error'})}});
server.listen(PORT,HOST,()=>console.log(`Fatehpur QuickDrop V14 running on http://localhost:${PORT}`));
